### ISSUE TITLE
Error at launch

### ISSUE THREAD

**Issue by trancanh1102** [RL-PucPR/tft-rl-bot#1]
I have problems launching even though I have fully installed as required

![image](https://user-images.githubusercontent.com/40576239/120090099-22b4e600-c12a-11eb-8993-c7f72e2fde1d.png)

Thanks for reading my question

**Comment by lucasrsa** [comment]
Hi, I fixed the issue, ScreenInterpreter was moved but this import was left unchanged. There should be no issues now.

Keep in mind that this is a project still in development and all that it does for now is read your gold and store from the game.
